name: jaguar_serializer_cli
version: 2.2.8
description: Platform and format agnostic serializer built using source_gen
homepage: https://github.com/Jaguar-dart/jaguar_serializer

environment:
    sdk: ">=2.15.1 <3.0.0"

dependencies:
    jaguar_serializer: ^2.2.2
    analyzer: ^3.2.0
    build: ^2.2.1
    logging: ^1.0.2
    source_gen: ^1.2.1
    meta: ^1.7.0

dev_dependencies:
    test: ^1.20.1
    build_runner: ^2.1.7
    build_web_compilers: ^3.2.2
    build_test: ^2.1.5
    collection: ^1.15.0
