name: jaguar_serializer
version: 2.2.12
description: Platform and format agnostic serializer built using source_gen
homepage: https://github.com/Jaguar-dart/jaguar_serializer
documentation:

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  build_runner: ^1.9.0
  jaguar_serializer_cli:
    path: ../serializer_cli