name: jaguar_serializer_protobuf
version: 2.2.2
description: Protobuf support for Jaguar serializer. Provides CodecRepo and SerializerRepo.
homepage: https://github.com/Jaguar-dart/jaguar_serializer_protobuf
documentation:

environment:
    sdk: ">=2.15.1 <3.0.0"

dependencies:
    jaguar_serializer:
        path: ../serializer
    protobuf: ^2.0.1

dev_dependencies:
