name: jaguar_serializer_mongo
description: MongoDB serializer helpers for jaguar_serializer
version: 2.2.1
publish_to: none
homepage: https://github.com/Jaguar-dart/jaguar_serializer
documentation:

environment:
    sdk: ">=2.15.1 <3.0.0"

dependencies:
    mongo_dart: ^0.7.4
    jaguar_serializer:
        path: ../serializer

dev_dependencies:
    test: ^1.20.1
    build_runner: ^2.1.7
    jaguar_serializer_cli:
        path: ../serializer_cli
